packages:
  - packages/*

overrides:
  js-yaml: '>=4.1.1'
  node-forge: '>=1.3.2'
  react-copy-to-clipboard>react: '>=19'
  react-helmet-async>react: '>=19'
  conventional-changelog-conventionalcommits: '>=8.0.0'

onlyBuiltDependencies:
  - cypress
  - lefthook
