name: Checks

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_VERSION: '16'

on:
  push:
    branches: [main]
  pull_request:
    types: [
        synchronize, # PR was updated
        opened, # PR was open
        reopened, # PR was closed and is now open again
        ready_for_review, # PR was converted from draft to open
      ]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Check Docs
        run: npm run check-docs

      - name: Check Typing
        run: npm run check-typing

      - name: Check Formatting
        run: npm run check-formatting

      - name: Lint
        run: npm run lint

      - name: Check Prepack
        run: npm run prepack
