name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    types: [
        synchronize, # PR was updated
        opened, # PR was open
        reopened, # PR was closed and is now open again
        ready_for_review, # PR was converted from draft to open
      ]

concurrency:
  group: 'unit-tests'
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Run Unit Tests and generate coverage
        run: pnpm test:coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2

      - name: Run Mutation Tests
        if: github.event_name == 'pull_request'
        run: pnpm test:mutation

      - name: Run Mutation Tests and publish reports
        if: github.event_name != 'pull_request'
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
        run: pnpm test:mutation-report

      - name: Run Unit Test in dist
        run: |
          pnpm pack
          tar zxvf *.tgz
          pnpm test:bundle
